# Generated by Django 3.2.9 on 2021-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_alter_counter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='period',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
